name: email-testing-server
version: '1.0.0'
summary: Email Testing Server
description: A cross-platform desktop application to test emails locally.

grade: stable
confinement: strict
base: core24

apps:
  email-testing-server:
    command: email-testing-server
    plugs: [network, network-bind, desktop, audio-playback, x11, wayland]
    desktop: meta/gui/email-testing-server.desktop # path inside snap (remains the same target)

parts:
  email-testing-server:
    plugin: dump
    # Set the source to the root of your project directory.
    # This means 'snapcraft' will work from 'PROJECT_ROOT' as its base.
    source: . # Go up one level from 'snap/' to 'PROJECT_ROOT/'
    # Specify all files to stage from the 'source' directory (which is now 'PROJECT_ROOT/').
    # Paths here are relative to your project root.
    stage:
      - dist/email-testing-server         # Path to your executable within dist/
      - email-testing-server.desktop      # Desktop file in project root
      - assets/icon.png                   # Icon in assets/icons
    organize:
      # Map the staged files to their final destination *inside the snap*.
      # Paths on the left are relative to the *part's install directory*
      # (where 'stage' put them).
      email-testing-server: email-testing-server
      email-testing-server.desktop: meta/gui/email-testing-server.desktop
      assets/icon.png: meta/gui/email-testing-server.png
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-libav
      - libglib2.0-0
      - libgtk-3-0